version: "3.7"

services:
  app:
    container_name: doodle_app
    ports:
      - 3001:3001
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    # environment:
    #   - DB_HOST: mysql
    depends_on:
      - mysql
      - redis
    networks:
      - default

  # fe:
  #   container_name: doodle_fe
  #   ports:
  #     - 3000:3000
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
  #   restart: always
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - /app/frontend/node_modules
  #   depends_on:
  #     - app
  #   networks:
  #     - default

  mailhog:
    image: mailhog/mailhog
    container_name: doodle_mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: doodle_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doodle
      MYSQL_USER: abc
      MYSQL_PASSWORD: p4ssword
    networks:
      - default

  phpmyadmin:
    container_name: doodle_pma
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASS_ROOT:-root}
      - PMA_PORT=${DB_PORT:-3306}
    depends_on:
      - mysql
    networks:
      - default

  redis:
    image: redis:5-alpine
    container_name: doodle_redis
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    environment:
      - REDIS_URL= redis:6379
    networks:
      - default

  redis-commander:
    container_name: doodle-redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    container_name: doodle_nginx
    restart: always
    ports:
      - 8181:80
    depends_on:
      - app
    volumes:
      # - ./backend:/app/backend
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - default

  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    volumes:
      - ./docker/minio:/data
    networks:
      - default

networks:
  default:
    driver: bridge
